In [1]:

import glob, os
import os.path as op
import pandas as pd
import numpy as np


In [2]:
#Get subject number
dset_dir = "/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/"
subjects = [file.split('/')[-1] for file in sorted(glob.glob(op.join(dset_dir, "sub-*")))]
subjects

['sub-101',
 'sub-102',
 'sub-103',
 'sub-104',
 'sub-106',
 'sub-107',
 'sub-108',
 'sub-110',
 'sub-212',
 'sub-213',
 'sub-214',
 'sub-215',
 'sub-216',
 'sub-217',
 'sub-218',
 'sub-219',
 'sub-320',
 'sub-321',
 'sub-322',
 'sub-323',
 'sub-324',
 'sub-325',
 'sub-327',
 'sub-328',
 'sub-329',
 'sub-330',
 'sub-331',
 'sub-332',
 'sub-333',
 'sub-334',
 'sub-335',
 'sub-336',
 'sub-337',
 'sub-338',
 'sub-339',
 'sub-340',
 'sub-341',
 'sub-342',
 'sub-343',
 'sub-344',
 'sub-345',
 'sub-346',
 'sub-347',
 'sub-348',
 'sub-349',
 'sub-350',
 'sub-451',
 'sub-452',
 'sub-453',
 'sub-455',
 'sub-456',
 'sub-457',
 'sub-458',
 'sub-459',
 'sub-460',
 'sub-462',
 'sub-463',
 'sub-464',
 'sub-465',
 'sub-467',
 'sub-468',
 'sub-469',
 'sub-470',
 'sub-502',
 'sub-503',
 'sub-571',
 'sub-572',
 'sub-573',
 'sub-574',
 'sub-575',
 'sub-577',
 'sub-578',
 'sub-579',
 'sub-580',
 'sub-581',
 'sub-582',
 'sub-584',
 'sub-585',
 'sub-586',
 'sub-587',
 'sub-588',
 'sub-589',
 'sub-590',
 'su

In [14]:
#Check files
for sub in subjects:
     if len(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci*.tsv'))) != 12:
        continue
#Ensuring that each subjects IDConn event files aren't empty and have the correct column names
     for IDConn_file in sorted(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci_run-[1-3]_events.tsv'))):
        df = pd.read_table(IDConn_file)
        if (len(df) != 18):
            print("WARNING, for",sub, 'rows = ', len(df))
        if list(df.columns[:]) != ['onset', 'duration', 'trial_type']:
            print("WARNING, for",sub,'column names are :', list(df.columns[:]))
#Ensuring that each subjects official event files aren't empty and have the correct column names
     for event_file in sorted(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci_run-[1-3]_acq-official_events.tsv'))):
        df = pd.read_table(event_file)
        if (len(df)) != 18:
            print("WARNING, for",sub, 'rows = ', len(df))
        if list(df.columns[:]) != ['onset', 'duration', 'trial_type', 'trial_phase']:
            print("WARNING, for",sub,'column names are :', list(df.columns[:]))
    #Checking if onset and duration for each subjects official and IDConn event files match
     for official_event_file in sorted(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci_run-[1-3]_acq-official_events.tsv'))):
            official_df = pd.read_table(official_event_file)
            official_data = official_df[["onset", "duration"]].values
            idconn_event_file = official_event_file.replace("_acq-official", "")
            idconn_df = pd.read_table(idconn_event_file)
            idconn_data = idconn_df[["onset", "duration"]].values
            if not np.array_equal(official_data, idconn_data):
                #f' {sub} doesn't work in python 2
                print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,official_event_file, idconn_event_file)
                print(official_data)
                print(idconn_data)
                
                
        
        
        

('WARNING:', 'sub-101', 'onset and/or duration DO NOT MATCH for', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-1_acq-official_events.tsv', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-1_events.tsv')
[[   4.       8.05 ]
 [  12.05     5.65 ]
 [  17.7     14.649]
 [  59.199    5.166]
 [  64.365    4.433]
 [  68.798    7.033]
 [ 114.38     4.484]
 [ 118.864    5.399]
 [ 124.263    1.617]
 [ 169.562    6.45 ]
 [ 176.012    5.3  ]
 [ 181.312    5.699]
 [ 224.744    5.216]
 [ 229.96     6.983]
 [ 236.943    0.85 ]
 [ 279.925    4.534]
 [ 284.459    3.233]
 [ 287.692    4.083]]
[[   4.       8.983]
 [  12.983    8.283]
 [  21.266    1.833]
 [  59.182    8.917]
 [  68.099    1.933]
 [  70.032    7.983]
 [ 114.348    5.683]
 [ 120.031    6.183]
 [ 126.214    2.234]
 [ 169.547    8.566]
 [ 178.113    2.417]
 [ 180.53    15.583]
 [ 224.713    8.633]
 [ 233.346    5.333]
 [ 238.679   19.716]
 [ 27

In [6]:
len(glob.glob(op.join(dset_dir, 'sub-*/ses-*/func/*fci_run-[1-3]_acq-official_events.tsv')))

642

In [7]:
len(glob.glob(op.join(dset_dir, 'sub-*/ses-*/func/*fci_run-[1-3]_events.tsv')))

642

In [13]:
#Session 1
#Nore IDConn files are currenty have the extension '_events.tsv'
order = [0,2,4,1,3,5]
for sub in subjects:
    #Get both the IDConn file from dset v2 and reference file from dset v1 (in Katie's folder)
    for IDConn_file, reference in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-1/func/*fci_run-[1-3]_events.tsv'))), sorted(glob.glob(op.join('/home/data/nbc/Laird_PhysicsLearning/dset-v1.0.0/derivatives/idconn-preproc',sub, 'ses-pre/func/*fci_run-[0-2]_events.tsv')))):
        #Get every third onset value, which should correspond to the beginning of each question. Sum duration to obtain the duration of the entire trial 
        df = pd.read_table(IDConn_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        IDConn_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #official files are the actual events files in dset 2 but have the extension  '_acq-official_events'
        official_file = IDConn_file.replace('_events', '_acq-official_events')
        df = pd.read_table(official_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #reference file
        df = pd.read_table(reference)
        reference_file = df[['onset', 'duration']].values                        
        #If not statements to see if onset and duration are equal
        #Comparing official files to reference
        if not np.allclose(official_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, official_file)
            print(official_combined_onset_duration_ordered)
            print(reference_file)
        #Else statement to see if the if statement actually works and isn't being skipped over
        else:
            print('official files fine for', sub)
        # Comparing IDConn files to reference
        if not np.allclose(IDConn_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, IDConn_file)
            print(reference_file)
            print(IDConn_combined_onset_duration_ordered)
        else:
            print('IDConn files fine for', sub)
                        

('WARNING:', 'sub-101', 'onset and/or duration DO NOT MATCH for', '/home/data/nbc/Laird_PhysicsLearning/dset-v1.0.0/derivatives/idconn-preproc/sub-101/ses-pre/func/sub-101_ses-pre_task-fci_run-0_events.tsv', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-1_acq-official_events.tsv')
[[   4.      28.349]
 [ 114.38    11.5  ]
 [ 224.744   13.049]
 [  59.199   16.632]
 [ 169.562   17.449]
 [ 279.925   11.85 ]]
[[   4.      19.099]
 [ 114.348   14.1  ]
 [ 224.713   33.682]
 [  59.182   18.833]
 [ 169.547   26.566]
 [ 279.895   16.383]]
('IDConn files fine for', 'sub-101')
('WARNING:', 'sub-101', 'onset and/or duration DO NOT MATCH for', '/home/data/nbc/Laird_PhysicsLearning/dset-v1.0.0/derivatives/idconn-preproc/sub-101/ses-pre/func/sub-101_ses-pre_task-fci_run-1_events.tsv', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-2_acq-official_events.tsv')
[[   4.      14.849]
 [ 114.346   15.883]
 [ 

In [46]:
#Session 2
for sub in subjects:
    #Get both the IDConn file from dset v2 and reference file from dset v1 (in KAtie's folder)
    for IDConn_file, reference in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-2/func/*fci_run-[1-3]_events.tsv'))), sorted(glob.glob(op.join('/home/data/nbc/Laird_PhysicsLearning/dset-v1.0.0/derivatives/idconn-preproc',sub, 'ses-post/func/*fci_run-[0-2]_events.tsv')))):
        #Get every third onset value, which should correspond to the beginning of each question. Sum duration to obtain the duration of the entire trial 
        df = pd.read_table(IDConn_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        IDConn_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #official files are the actual events files in dset 2
        official_file = IDConn_file.replace('_events', '_acq-official_events')
        df = pd.read_table(official_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #reference file
        df = pd.read_table(reference)
        reference_file = df[['onset', 'duration']].values                        
        #If not statements to see if onset and duration are equal
        #Comparing official files to reference
        if not np.allclose(official_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, official_file)
            print(official_combined_onset_duration_ordered)
            print(reference_file)
        else:
            print('official files fine for', sub)
        # Comparing IDConn files to reference
        if not np.allclose(IDConn_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, IDConn_file)
            print(reference_file)
            print(IDConn_combined_onset_duration_ordered)
        else:
            print('IDConn files fine for', sub)

('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-106')
('IDConn files fine for', 'sub-106')
('official f

In [15]:
#Check is IDConn Session 1 & 2 Match
for sub in subjects:
     if len(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci*.tsv'))) != 12:
        continue
     for IDConn_file_ses1, IDConn_file_ses2 in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-1/func/*fci_run-[1-3]_events.tsv'))),sorted(glob.glob(op.join(dset_dir,sub, 'ses-2/func/*fci_run-[1-3]_events.tsv')))):
        df = pd.read_table(IDConn_file_ses1)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        IDConn_ses_1_file = np.vstack(([combined_onset_duration[i] for i in order])) 
        ##   
        df = pd.read_table(IDConn_file_ses2)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        IDConn_ses_2_file = np.vstack(([combined_onset_duration[i] for i in order]))   
     if np.array_equal(IDConn_ses_1_file, IDConn_ses_2_file):
        print("WARNING:", sub, "onset and/or duration MATCH" ,IDConn_file_ses1, IDConn_file_ses2)
        print(IDConn_ses_1_file)
        print(IDConn_ses_2_file)
     else:
        print('IDConn ses 1 & 2 files do not match for', sub)                                           
        

('IDConn ses 1 & 2 files do not match for', 'sub-101')
('IDConn ses 1 & 2 files do not match for', 'sub-102')
('IDConn ses 1 & 2 files do not match for', 'sub-103')
('IDConn ses 1 & 2 files do not match for', 'sub-104')
('IDConn ses 1 & 2 files do not match for', 'sub-106')
('IDConn ses 1 & 2 files do not match for', 'sub-107')
('IDConn ses 1 & 2 files do not match for', 'sub-108')
('IDConn ses 1 & 2 files do not match for', 'sub-110')
('IDConn ses 1 & 2 files do not match for', 'sub-212')
('IDConn ses 1 & 2 files do not match for', 'sub-214')
('IDConn ses 1 & 2 files do not match for', 'sub-215')
('IDConn ses 1 & 2 files do not match for', 'sub-216')
('IDConn ses 1 & 2 files do not match for', 'sub-217')
('IDConn ses 1 & 2 files do not match for', 'sub-218')
('IDConn ses 1 & 2 files do not match for', 'sub-219')
('IDConn ses 1 & 2 files do not match for', 'sub-320')
('IDConn ses 1 & 2 files do not match for', 'sub-321')
('IDConn ses 1 & 2 files do not match for', 'sub-323')
('IDConn s

In [16]:
#Check if session 1 and 2 for the official files match. Problematic files in session 1 are actualle session 2 files
for sub in subjects:
     if len(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci*.tsv'))) != 12:
        continue
    #session 1 file
     for official_file_ses1, official_file_ses2 in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-1/func/*fci_run-[1-3]_acq-official_events.tsv'))),sorted(glob.glob(op.join(dset_dir,sub, 'ses-2/func/*fci_run-[1-3]_acq-official_events.tsv')))):
        df = pd.read_table(official_file_ses1)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_ses_1_file = np.vstack(([combined_onset_duration[i] for i in order])) 
        ##Session 2 files   
        df = pd.read_table(official_file_ses2)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_ses_2_file = np.vstack(([combined_onset_duration[i] for i in order]))   
        if np.allclose(official_ses_1_file, official_ses_2_file):
            print("WARNING:", sub, "onset and/or duration MATCH" ,official_file_ses1, official_file_ses2)
            print(official_ses_1_file)
            print(official_ses_2_file)
        else:
            print('Official ses 1 & 2 files do not match for', sub) 

('WARNING:', 'sub-101', 'onset and/or duration MATCH', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-1_acq-official_events.tsv', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-2/func/sub-101_ses-2_task-fci_run-1_acq-official_events.tsv')
[[   4.      28.349]
 [ 114.38    11.5  ]
 [ 224.744   13.049]
 [  59.199   16.632]
 [ 169.562   17.449]
 [ 279.925   11.85 ]]
[[   4.      28.349]
 [ 114.38    11.5  ]
 [ 224.744   13.049]
 [  59.199   16.632]
 [ 169.562   17.449]
 [ 279.925   11.85 ]]
('WARNING:', 'sub-101', 'onset and/or duration MATCH', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-1/func/sub-101_ses-1_task-fci_run-2_acq-official_events.tsv', '/home/data/nbc/Laird_PhysicsLearning/dset-v2.0.0/sub-101/ses-2/func/sub-101_ses-2_task-fci_run-2_acq-official_events.tsv')
[[   4.      14.849]
 [ 114.346   15.883]
 [ 224.71    10.999]
 [  59.165   15.832]
 [ 169.528   18.949]
 [ 279.891   15.4  ]]
[[   4.      

In [17]:
#After correcting files
for sub in subjects:
     if len(glob.glob(op.join(dset_dir, sub,'ses-*/func/*fci*.tsv'))) != 12:
        continue
    #session 1 file
     for official_file_ses1, official_file_ses2 in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-1/func/*fci_run-[1-3]_acq-official_events.tsv'))),sorted(glob.glob(op.join(dset_dir,sub, 'ses-2/func/*fci_run-[1-3]_acq-official_events.tsv')))):
        df = pd.read_table(official_file_ses1)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_ses_1_file = np.vstack(([combined_onset_duration[i] for i in order])) 
        ##Session 2 files   
        df = pd.read_table(official_file_ses2)    
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_ses_2_file = np.vstack(([combined_onset_duration[i] for i in order]))   
        if np.allclose(official_ses_1_file, official_ses_2_file):
            print("WARNING:", sub, "onset and/or duration MATCH" ,official_file_ses1, official_file_ses2)
            print(official_ses_1_file)
            print(official_ses_2_file)
        else:
            print('Official ses 1 & 2 files do not match for', sub) 

('Official ses 1 & 2 files do not match for', 'sub-101')
('Official ses 1 & 2 files do not match for', 'sub-101')
('Official ses 1 & 2 files do not match for', 'sub-101')
('Official ses 1 & 2 files do not match for', 'sub-102')
('Official ses 1 & 2 files do not match for', 'sub-102')
('Official ses 1 & 2 files do not match for', 'sub-102')
('Official ses 1 & 2 files do not match for', 'sub-103')
('Official ses 1 & 2 files do not match for', 'sub-103')
('Official ses 1 & 2 files do not match for', 'sub-103')
('Official ses 1 & 2 files do not match for', 'sub-104')
('Official ses 1 & 2 files do not match for', 'sub-104')
('Official ses 1 & 2 files do not match for', 'sub-104')
('Official ses 1 & 2 files do not match for', 'sub-106')
('Official ses 1 & 2 files do not match for', 'sub-106')
('Official ses 1 & 2 files do not match for', 'sub-106')
('Official ses 1 & 2 files do not match for', 'sub-107')
('Official ses 1 & 2 files do not match for', 'sub-107')
('Official ses 1 & 2 files do n

In [18]:
#Session 1 After Correcting
#Nore IDConn files are currenty have the extension '_events.tsv'
order = [0,2,4,1,3,5]
for sub in subjects:
    #Get both the IDConn file from dset v2 and reference file from dset v1 (in Katie's folder)
    for IDConn_file, reference in zip(sorted(glob.glob(op.join(dset_dir,sub, 'ses-1/func/*fci_run-[1-3]_events.tsv'))), sorted(glob.glob(op.join('/home/data/nbc/Laird_PhysicsLearning/dset-v1.0.0/derivatives/idconn-preproc',sub, 'ses-pre/func/*fci_run-[0-2]_events.tsv')))):
        #Get every third onset value, which should correspond to the beginning of each question. Sum duration to obtain the duration of the entire trial 
        df = pd.read_table(IDConn_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        IDConn_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #official files are the actual events files in dset 2 but have the extension  '_acq-official_events'
        official_file = IDConn_file.replace('_events', '_acq-official_events')
        df = pd.read_table(official_file)
        data = df[['onset', 'duration']].values
        combined_onset_duration = np.vstack((data[::3,0],np.hstack(([np.sum(data[:,1][0:3]),np.sum(data[:,1][3:6]), np.sum(data[:,1][6:9]), np.sum(data[:,1][9:12]),np.sum(data[:,1][12:15]), np.sum(data[:,1][15:19])])))).T
        official_combined_onset_duration_ordered = np.vstack(([combined_onset_duration[i] for i in order]))
        #reference file
        df = pd.read_table(reference)
        reference_file = df[['onset', 'duration']].values                        
        #If not statements to see if onset and duration are equal
        #Comparing official files to reference
        if not np.allclose(official_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, official_file)
            print(official_combined_onset_duration_ordered)
            print(reference_file)
        #Else statement to see if the if statement actually works and isn't being skipped over
        else:
            print('official files fine for', sub)
        # Comparing IDConn files to reference
        if not np.allclose(IDConn_combined_onset_duration_ordered, reference_file):
            print("WARNING:", sub, "onset and/or duration DO NOT MATCH for" ,reference, IDConn_file)
            print(reference_file)
            print(IDConn_combined_onset_duration_ordered)
        else:
            print('IDConn files fine for', sub)

('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-101')
('IDConn files fine for', 'sub-101')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-102')
('IDConn files fine for', 'sub-102')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-103')
('IDConn files fine for', 'sub-103')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-104')
('IDConn files fine for', 'sub-104')
('official files fine for', 'sub-106')
('IDConn files fine for', 'sub-106')
('official f